"""Per-politician coverage report across the scraped corpus.

Where `dataset_stats.py` summarises each *source file* (article/word/date counts),
this answers the other question we need for the all-MPs goal: **who do we actually
have data on?** It scans every scraped article and, for each politician in the
roster (`mps_roster.json`), counts how many articles mention them, over what date
range, from how many distinct sources — then flags the coverage gaps.

A politician "covers" an article if a full-name alias appears in the headline/
body, or they are the article's author (party press releases). Bare-surname
matches are reported separately (noisier — common surnames collide).

Stdlib only; no API key or network.

    python corpus_report.py                          # scans ./ and ./data for *.json[l]
    python corpus_report.py --out CORPUS_REPORT.md
    python corpus_report.py data/mvp_hansard.json    # explicit files
"""

import glob
import json
import os
import re
import sys
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
DATE_RE = re.compile(r"(\d{4})-(\d{2})-(\d{2})")


def _fold(s):
    """Lowercase + strip accents/macrons so 'Menéndez' matches 'menendez'."""
    return unicodedata.normalize("NFKD", s or "").encode("ascii", "ignore").decode().lower()


def _date_key(value):
    m = DATE_RE.search(str(value or ""))
    return f"{m.group(1)}-{m.group(2)}-{m.group(3)}" if m else None


def _load_articles(path):
    """Load a JSON array (sources.py) or JSONL (hansard.py, one record/line)."""
    with open(path) as f:
        text = f.read().strip()
    if not text:
        return []
    try:
        data = json.loads(text)
        return data if isinstance(data, list) else [data]
    except json.JSONDecodeError:
        return [json.loads(line) for line in text.splitlines() if line.strip()]


def load_roster(path):
    with open(path, encoding="utf-8") as f:
        roster = json.load(f)
    for r in roster:
        aliases = r.get("aliases", [])
        r["_full"] = [a for a in aliases if " " in a]          # full names — precise
        r["_surnames"] = [a for a in aliases if " " not in a]  # single token — noisy
    return roster


def discover():
    skip = {"mps_roster.json"}
    files = sorted(set(glob.glob(os.path.join(HERE, "*.json")) +
                       glob.glob(os.path.join(HERE, "data", "*.json")) +
                       glob.glob(os.path.join(HERE, "data", "*.jsonl"))))
    return [f for f in files if os.path.basename(f) not in skip]


def _surname_word_re(surname):
    return re.compile(r"\b" + re.escape(surname) + r"\b")


def scan(files, roster):
    # per-politician id -> stats
    stats = {r["id"]: {"name": r["name"], "party": r["party"], "articles": 0,
                       "surname_only": 0, "sources": set(), "dates": []} for r in roster}
    surname_res = {r["id"]: [_surname_word_re(s) for s in r["_surnames"]] for r in roster}
    n_articles = 0

    for path in files:
        source = os.path.splitext(os.path.basename(path))[0]
        try:
            articles = _load_articles(path)
        except Exception as e:  # noqa: BLE001
            print(f"skip {path}: {e}", file=sys.stderr)
            continue
        for a in articles:
            n_articles += 1
            text = _fold(a.get("headline", "") + "\n" + a.get("content", ""))
            author = _fold(a.get("author", ""))
            date = _date_key(a.get("date"))
            for r in roster:
                full_hit = any(name in text or name in author for name in r["_full"])
                if full_hit:
                    s = stats[r["id"]]
                    s["articles"] += 1
                    s["sources"].add(source)
                    if date:
                        s["dates"].append(date)
                elif any(rx.search(text) for rx in surname_res[r["id"]]):
                    stats[r["id"]]["surname_only"] += 1
    return stats, n_articles


def render(stats, n_articles, n_files):
    rows = sorted(stats.values(), key=lambda s: (-s["articles"], s["name"]))
    covered = [s for s in rows if s["articles"] > 0]
    buckets = {"20+": 0, "5–19": 0, "1–4": 0, "0": 0}
    for s in rows:
        n = s["articles"]
        buckets["20+" if n >= 20 else "5–19" if n >= 5 else "1–4" if n >= 1 else "0"] += 1

    L = ["# Corpus coverage by politician", "",
         f"Generated by `corpus_report.py` over **{n_articles:,} articles** in "
         f"{n_files} file(s), against a roster of **{len(rows)} politicians**.", "",
         "A politician covers an article if a full-name match appears in the "
         "headline/body or author. *Surname-only* hits (noisier) are listed apart.", "",
         "## Coverage summary", "",
         f"- **{len(covered)}/{len(rows)}** politicians have ≥1 article.",
         f"- By volume: {buckets['20+']} with 20+, {buckets['5–19']} with 5–19, "
         f"{buckets['1–4']} with 1–4, {buckets['0']} with none.", "",
         "## Per-politician", "",
         "| Politician | Party | Articles | Sources | Date range | Surname-only |",
         "|---|---|---|---|---|---|"]
    for s in rows:
        dr = f"{min(s['dates'])} → {max(s['dates'])}" if s["dates"] else "—"
        L.append(f"| {s['name']} | {s['party'] or '?'} | {s['articles']} | "
                 f"{len(s['sources'])} | {dr} | {s['surname_only']} |")

    gaps = [s["name"] for s in rows if s["articles"] == 0]
    L += ["", "## Coverage gaps (zero full-name articles)", ""]
    L.append(", ".join(gaps) if gaps else "_None — every rostered politician has coverage._")
    L.append("")
    return "\n".join(L)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    out = None
    roster_path = os.path.join(HERE, "mps_roster.json")
    for a in sys.argv[1:]:
        if a.startswith("--out"):
            out = a.split("=", 1)[1] if "=" in a else "CORPUS_REPORT.md"
        elif a.startswith("--roster="):
            roster_path = a.split("=", 1)[1]
    files = args or discover()
    roster = load_roster(roster_path)
    stats, n_articles = scan(files, roster)
    report = render(stats, n_articles, len(files))
    print(report)
    if out:
        with open(out, "w", encoding="utf-8") as f:
            f.write(report)
        print(f"\nWrote {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
