[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scrapers"
version = "0.1.0"
authors = [
  { name="act65", email="te1farac@gmail.com" },
]
description = "A sample project"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.28",
    "numpy"
]

[tool.setuptools.packages]
where = ["scrapers"]